#!/bin/bash

# --------
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# --------
#
# Author: http://Gainroot.co and J Gifford
# Acknowledgement is given to J Lynch for the bright idea
#
# Version 0.93, 20110901
#
# Tested with a default Ubuntu 10.04 LTS installation. (uname -rvmo)
# 2.6.32-28-generic-pae #55-Ubuntu SMP Mon Jan 10 22:34:08 UTC 2011 i686 GNU/Linux
# Your mileage may vary.
#
# Usage: ./install.sh {server|client|web}
#
# Installs OpenERP Server, Client and/or Web on a Ubuntu or Ubuntu-like system.
#
# The installation resulting from these files would be good for a demo or
# proof-of-concept environment but would __not be recommended for production__.
#

# See README for more details
#

# ---------------------------------------------------------
# Below are some variables you can modify
SCRIPTNAME=$0
BASE=`dirname $SCRIPTNAME`
#SERVER_CONFIGFILE=$BASE/init-files/openerp-server.cfg
#SERVER_CONFIGDEST=/etc/openerp-server.cfg
SERVER=openerp-server
#WEB_CONFIGFILE=$BASE/init-files/openerp-web.cfg
#WEB_CONFIGDEST=/etc/openerp-web.cfg
CONFIG_MODE=640
INIT_MODE=755
WEB=openerp-web
#INITFILES=$BASE/init-files
#DEBUG="true"
USER=openerp
# That's all, stop editing!
# ---------------------------------------------------------

[ -n "$DEBUG" ] && echo "BASE=$BASE"
[ -n "$DEBUG" ] && echo `ls -l $BASE/init-files/openerp-server`

#
# Function that creates a user if needed
#
create_user()
{
    if [ -n $USER ]; then
        # try to create USER; exit if fails
	/usr/bin/id $USER >/dev/null 2>&1
	RETVAL=$?
	if [ $RETVAL -ne 0 ]; then
	    echo "User $USER doesn't exist, creating . . ."
	    sudo adduser --system --group $USER
	    RETVAL=$?
	    if [ $RETVAL -ne 0 ]; then
		echo "User $USER failed to create, exiting . . ."
		exit 1
	    fi
	fi
    else
	echo "No user provided, exiting . . ."
	exit 1
    fi
}

#
# Function to install config file
# Takes one argument, the name of the config FILE
#
install_config_file()
{
    FILE=$1
    [ -n "$DEBUG" ] && echo $FILE

    # Install config file
    sudo install -b -c -g $USER -m $CONFIG_MODE -o root $BASE/init-files/$FILE /etc/$FILE
    # Remember, -b creates backup files with a tilde suffix: FILE~
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
	echo "Failed to install config file: $FILE"
    fi
}

#
# Function to install init file
# Takes one argument, the name of the init FILE
#
install_init_file()
{
    FILE=$1
    [ -n "$DEBUG" ] && echo $FILE

    # install init file
    sudo install -b -c -g root -m $INIT_MODE -o root $BASE/init-files/$FILE /etc/init.d/$FILE
    # Remember, -b creates backup files with a tilde suffix: FILE~
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
	echo "Failed to install init file: $FILE"
    fi
}

#
# Function to link init file into correct RC levels
#
link_init_file()
{
    FILE=$1
    [ -n "$DEBUG" ] && echo $FILE

    sudo update-rc.d $FILE defaults
    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
	echo "Failed to propagate init file: $FILE"
    fi
}

case "$1" in
  server)
	# set LOGFILE
	LOGFILE=~/openERP_$1_install.log

	# install OpenERP Server
	$BASE/openERP/server.sh #$LOGFILE

	# create the openerp user
	create_user #$USER

	# install the config file in /etc
	install_config_file $SERVER.cfg

	# install the init file in /etc/rc.d
	install_init_file $SERVER

	# Propagate openerp-server init file into correct RC levels
	link_init_file $SERVER

	# Done
	echo "Done. Please check above messages and/or $LOGFILE for errors."
	echo "If none found, start OpenERP Server by typing:"
	echo "sudo /etc/init.d/openerp-server start"
	;;
  client)
	# set LOGFILE
	LOGFILE=~/openERP_$1_install.log

	# Install OpenERP Client
	$BASE/openERP/client.sh #$LOGFILE

	# Done
	echo "Done. Please check above messages for errors."
	;;
  web)
	# set LOGFILE
	LOGFILE=~/openERP_$1_install.log

	# install OpenERP Web
	$BASE/openERP/web.sh #$LOGFILE

	# create the openerp user
	create_user #$USER

	# install the config file in /etc
	install_config_file $WEB.cfg

	# install the init file in /etc/rc.d
	install_init_file $WEB

	# Propagate openerp-server init file into correct RC levels
	link_init_file $WEB

	# Done
	echo "Done. Please check above messages and/or $LOGFILE for errors."
	echo "If none found, start OpenERP Web by typing:"
	echo "sudo /etc/init.d/openerp-web start"
	;;
  *)
	echo "Usage: $SCRIPTNAME {server|client|web}" >&2
	echo "Installs OpenERP Server, Client or Web" >&2
	exit 3
	;;
esac
